server:
  port: 8082

spring:
  application:
    name: ming-rpc-consumer

# Ming RPC 配置
rpc:
  name: ming-rpc-consumer
  version: 1.0
  serverHost: localhost
  serverPort: 8080  # 这里是消费者，不会启动RPC服务器，但配置保持一致
  serializer: JDK
  loadBalancer: ROUND_ROBIN
  retryStrategy: NO
  tolerantStrategy: FAIL_FAST
  mock: false
  
  # 注册中心配置
  registryConfig:
    registry: MOCK
    address: http://localhost:2380
    timeout: 10000

# 日志配置
logging:
  level:
    com.ming: INFO
    com.ming.rpc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
