server:
  port: 8081

spring:
  application:
    name: ming-rpc-provider

# Ming RPC 配置
rpc:
  name: ming-rpc-provider
  version: 1.0
  serverHost: localhost
  serverPort: 8080
  serializer: JDK
  loadBalancer: ROUND_ROBIN
  retryStrategy: NO
  tolerantStrategy: FAIL_FAST
  mock: false
  
  # 注册中心配置
  registryConfig:
    registry: ETCD
    address: http://localhost:2380
    timeout: 10000

# 日志配置
logging:
  level:
    com.ming: INFO
    com.ming.rpc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
